"""
PowerPoint Generator
====================
Uses python-pptx to build a styled presentation from structured research data.

Slide layout
------------
  0 : Title slide (topic + subtitle)
  1 : Executive summary
  2+: One slide per section (title + bullets + citation footer)
  N-1: Data table slides (one per table)
  N : Sources / bibliography slide

Design choices
--------------
- Custom colour theme applied via direct RGB manipulation (no .thmx needed)
- Text wraps naturally in text frames
- Tables rendered using pptx Table object
"""

import uuid
from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Emu, Inches, Pt

# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------
_DARK_BLUE = RGBColor(26, 58, 110)
_MID_BLUE = RGBColor(52, 119, 189)
_LIGHT_GRAY = RGBColor(240, 242, 245)
_WHITE = RGBColor(255, 255, 255)
_DARK_TEXT = RGBColor(33, 37, 41)
_ACCENT = RGBColor(255, 186, 0)   # gold accent for bullets

# Standard 16:9 dimensions
_W = Inches(13.33)
_H = Inches(7.5)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _blank_prs() -> Presentation:
    prs = Presentation()
    prs.slide_width = _W
    prs.slide_height = _H
    return prs


def _blank_slide(prs: Presentation):
    """Add a slide with no layout placeholders (full manual control)."""
    blank_layout = prs.slide_layouts[6]  # 'Blank' layout
    return prs.slides.add_slide(blank_layout)


def _add_rect(slide, left, top, width, height, fill_color: RGBColor):
    from pptx.util import Emu
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        left, top, width, height,
    )
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    shape.line.fill.background()
    return shape


def _text_box(slide, left, top, width, height, text: str,
               font_size: int, bold: bool = False,
               color: RGBColor = _DARK_TEXT,
               align=PP_ALIGN.LEFT, wrap: bool = True) -> None:
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = wrap
    para = tf.paragraphs[0]
    para.alignment = align
    run = para.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.color.rgb = color


def _add_bullet_text(tf, bullets: list[str], font_size: int = 16,
                     color: RGBColor = _DARK_TEXT) -> None:
    for i, b in enumerate(bullets):
        if i == 0:
            para = tf.paragraphs[0]
        else:
            para = tf.add_paragraph()
        para.alignment = PP_ALIGN.LEFT
        run = para.add_run()
        run.text = f"\u2022  {b}"
        run.font.size = Pt(font_size)
        run.font.color.rgb = color


# ---------------------------------------------------------------------------
# Slide builders
# ---------------------------------------------------------------------------


def _title_slide(prs: Presentation, topic: str, language: str) -> None:
    slide = _blank_slide(prs)
    # Full-bleed background
    _add_rect(slide, 0, 0, _W, _H, _DARK_BLUE)
    # Gold accent bar
    _add_rect(slide, Inches(0.6), Inches(3.4), Inches(1.2), Inches(0.12), _ACCENT)
    # Topic title
    _text_box(slide, Inches(0.6), Inches(1.5), Inches(12), Inches(1.8),
               topic, 36, bold=True, color=_WHITE, align=PP_ALIGN.LEFT)
    subtitle = "Informe de Investigación Inteligente" if language == "es" else "Intelligent Research Report"
    _text_box(slide, Inches(0.6), Inches(3.6), Inches(8), Inches(0.5),
               subtitle, 18, color=_ACCENT, align=PP_ALIGN.LEFT)
    label = "Generado por Investigador Inteligente Multimodal" if language == "es" \
        else "Generated by Multimodal Intelligent Researcher"
    _text_box(slide, Inches(0.6), Inches(6.8), Inches(12), Inches(0.4),
               label, 10, color=RGBColor(180, 200, 220), align=PP_ALIGN.LEFT)


def _summary_slide(prs: Presentation, summary: str, language: str) -> None:
    slide = _blank_slide(prs)
    _add_rect(slide, 0, 0, _W, Inches(1.2), _DARK_BLUE)
    title = "Resumen Ejecutivo" if language == "es" else "Executive Summary"
    _text_box(slide, Inches(0.5), Inches(0.15), Inches(12), Inches(0.9),
               title, 24, bold=True, color=_WHITE)
    _add_rect(slide, Inches(0.5), Inches(1.4), Inches(12.3), Inches(5.6), _LIGHT_GRAY)
    # Body text
    txBox = slide.shapes.add_textbox(Inches(0.7), Inches(1.6), Inches(11.9), Inches(5.4))
    tf = txBox.text_frame
    tf.word_wrap = True
    para = tf.paragraphs[0]
    run = para.add_run()
    run.text = summary
    run.font.size = Pt(16)
    run.font.color.rgb = _DARK_TEXT


def _section_slide(prs: Presentation, section: dict, language: str) -> None:
    slide = _blank_slide(prs)
    _add_rect(slide, 0, 0, _W, Inches(1.2), _MID_BLUE)
    title = section.get("title", "")
    _text_box(slide, Inches(0.5), Inches(0.15), Inches(12), Inches(0.9),
               title, 22, bold=True, color=_WHITE)

    content = section.get("content", "")
    bullets = section.get("bullet_points", [])
    citations = section.get("citations", [])

    y_cursor = Inches(1.3)

    if content:
        # Truncate to keep slide readable
        excerpt = content[:500] + ("…" if len(content) > 500 else "")
        txBox = slide.shapes.add_textbox(Inches(0.5), y_cursor, Inches(12.3), Inches(3.5))
        tf = txBox.text_frame
        tf.word_wrap = True
        para = tf.paragraphs[0]
        run = para.add_run()
        run.text = excerpt
        run.font.size = Pt(13)
        run.font.color.rgb = _DARK_TEXT
        y_cursor += Inches(3.6)

    if bullets and y_cursor < Inches(6.5):
        txBox = slide.shapes.add_textbox(Inches(0.5), y_cursor, Inches(12.3), Inches(5.5))
        tf = txBox.text_frame
        tf.word_wrap = True
        _add_bullet_text(tf, bullets[:5], font_size=12)
        y_cursor += Inches(min(len(bullets) * 0.4, 2.0))

    # Citation footer
    if citations:
        cit_text = " | ".join(citations[:2])
        _text_box(slide, Inches(0.5), Inches(7.0), Inches(12.3), Inches(0.35),
                   cit_text[:180], 7, color=RGBColor(120, 120, 120))


def _table_slide(prs: Presentation, table_data: dict, language: str) -> None:
    from pptx.util import Inches, Pt
    headers = table_data.get("headers", [])
    rows = table_data.get("rows", [])
    title = table_data.get("title", "Data")
    if not headers or not rows:
        return

    slide = _blank_slide(prs)
    _add_rect(slide, 0, 0, _W, Inches(1.2), _DARK_BLUE)
    _text_box(slide, Inches(0.5), Inches(0.15), Inches(12), Inches(0.9),
               title, 22, bold=True, color=_WHITE)

    ncols = len(headers)
    nrows = len(rows) + 1  # +1 for header row
    col_w = Inches(12.3 / ncols)

    tbl = slide.shapes.add_table(nrows, ncols, Inches(0.5), Inches(1.4),
                                  Inches(12.3), Inches(min(nrows * 0.45, 5.5))).table

    for ci, h in enumerate(headers):
        cell = tbl.cell(0, ci)
        cell.text = str(h)
        cell.fill.solid()
        cell.fill.fore_color.rgb = _MID_BLUE
        para = cell.text_frame.paragraphs[0]
        para.alignment = PP_ALIGN.CENTER
        run = para.runs[0]
        run.font.bold = True
        run.font.size = Pt(11)
        run.font.color.rgb = _WHITE

    for ri, row in enumerate(rows, 1):
        fill_color = _LIGHT_GRAY if ri % 2 == 0 else _WHITE
        for ci, val in enumerate(row[:ncols]):
            cell = tbl.cell(ri, ci)
            cell.text = str(val)[:40]
            cell.fill.solid()
            cell.fill.fore_color.rgb = fill_color
            run = cell.text_frame.paragraphs[0].runs
            if run:
                run[0].font.size = Pt(10)


def _sources_slide(prs: Presentation, sources: list[dict], language: str) -> None:
    slide = _blank_slide(prs)
    _add_rect(slide, 0, 0, _W, Inches(1.2), _DARK_BLUE)
    label = "Bibliografía" if language == "es" else "Bibliography"
    _text_box(slide, Inches(0.5), Inches(0.15), Inches(12), Inches(0.9),
               label, 24, bold=True, color=_WHITE)

    txBox = slide.shapes.add_textbox(Inches(0.5), Inches(1.3), Inches(12.3), Inches(5.9))
    tf = txBox.text_frame
    tf.word_wrap = True

    for i, src in enumerate(sources[:12], 1):
        apa = src.get("citation_apa") or src.get("title", "")
        if i == 1:
            para = tf.paragraphs[0]
        else:
            para = tf.add_paragraph()
        run = para.add_run()
        run.text = f"[{i}] {apa[:200]}"
        run.font.size = Pt(9)
        run.font.color.rgb = _DARK_TEXT


# ---------------------------------------------------------------------------
# Public builder function
# ---------------------------------------------------------------------------


def build_pptx(
    topic: str,
    language: str,
    structured_data: dict,
    sources: list[dict],
    extra_instructions: str,
    output_dir: Path,
) -> Path:
    """
    Build a PowerPoint presentation and save it to output_dir.
    Returns the path to the generated .pptx file.
    """
    prs = _blank_prs()

    # 1. Title slide
    _title_slide(prs, topic, language)

    # 2. Extra instructions slide (if provided)
    if extra_instructions.strip():
        foreword_section = {
            "title": "Notas Adicionales" if language == "es" else "Additional Notes",
            "content": extra_instructions.strip(),
            "bullet_points": [],
            "citations": [],
        }
        _section_slide(prs, foreword_section, language)

    # 3. Executive summary
    summary = structured_data.get("executive_summary", "")
    if summary:
        _summary_slide(prs, summary, language)

    # 4. Key findings as a dedicated slide
    findings = structured_data.get("key_findings", [])
    if findings:
        label = "Hallazgos Clave" if language == "es" else "Key Findings"
        findings_section = {
            "title": label,
            "content": "",
            "bullet_points": [f.get("finding", "") for f in findings],
            "citations": [f.get("citation_apa", "") for f in findings if f.get("citation_apa")],
        }
        _section_slide(prs, findings_section, language)

    # 5. Content sections
    for section in structured_data.get("sections", []):
        _section_slide(prs, section, language)

    # 6. Data table slides
    for table in structured_data.get("data_tables", []):
        _table_slide(prs, table, language)

    # 7. Sources
    if sources:
        _sources_slide(prs, sources, language)

    filename = output_dir / f"{uuid.uuid4().hex}.pptx"
    prs.save(str(filename))
    return filename
